### ISSUE TITLE
第三次作业中的串操作指令表

### ISSUE THREAD

**Issue by ZoEplA** [DigBullTech-Michael/ctf_re#44]
这个只是字跟字节的关系吧，都是从端口DX输入
![Uploading 图片.png…]()

**Comment by ZoEplA** [comment]
![_20171122230339](https://user-images.githubusercontent.com/33739249/33133958-64737ffc-cfd9-11e7-9f87-17de7f98c0ec.png)

**Comment by DigApis-Michael** [comment]
@ZoEplA 是的。我也是这样理解的

**Comment by ZoEplA** [comment]
好的，谢谢!
